// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartExpense.Data;

#nullable disable

namespace SmartExpense.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartExpense.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Color = "#FF6B6B",
                            CreatedAt = new DateTime(2025, 12, 18, 16, 25, 35, 393, DateTimeKind.Utc).AddTicks(9645),
                            Icon = "🍔",
                            Name = "Food & Dining",
                            Type = "Expense"
                        },
                        new
                        {
                            CategoryId = 2,
                            Color = "#4ECDC4",
                            CreatedAt = new DateTime(2025, 12, 18, 16, 25, 35, 393, DateTimeKind.Utc).AddTicks(9650),
                            Icon = "🚗",
                            Name = "Transportation",
                            Type = "Expense"
                        },
                        new
                        {
                            CategoryId = 3,
                            Color = "#45B7D1",
                            CreatedAt = new DateTime(2025, 12, 18, 16, 25, 35, 393, DateTimeKind.Utc).AddTicks(9652),
                            Icon = "🛍️",
                            Name = "Shopping",
                            Type = "Expense"
                        },
                        new
                        {
                            CategoryId = 4,
                            Color = "#FFA07A",
                            CreatedAt = new DateTime(2025, 12, 18, 16, 25, 35, 393, DateTimeKind.Utc).AddTicks(9653),
                            Icon = "🎬",
                            Name = "Entertainment",
                            Type = "Expense"
                        },
                        new
                        {
                            CategoryId = 5,
                            Color = "#98D8C8",
                            CreatedAt = new DateTime(2025, 12, 18, 16, 25, 35, 393, DateTimeKind.Utc).AddTicks(9655),
                            Icon = "🏥",
                            Name = "Healthcare",
                            Type = "Expense"
                        },
                        new
                        {
                            CategoryId = 6,
                            Color = "#F7DC6F",
                            CreatedAt = new DateTime(2025, 12, 18, 16, 25, 35, 393, DateTimeKind.Utc).AddTicks(9656),
                            Icon = "📱",
                            Name = "Bills & Utilities",
                            Type = "Expense"
                        },
                        new
                        {
                            CategoryId = 7,
                            Color = "#BB8FCE",
                            CreatedAt = new DateTime(2025, 12, 18, 16, 25, 35, 393, DateTimeKind.Utc).AddTicks(9657),
                            Icon = "📚",
                            Name = "Education",
                            Type = "Expense"
                        },
                        new
                        {
                            CategoryId = 8,
                            Color = "#95A5A6",
                            CreatedAt = new DateTime(2025, 12, 18, 16, 25, 35, 393, DateTimeKind.Utc).AddTicks(9659),
                            Icon = "📦",
                            Name = "Others",
                            Type = "Expense"
                        },
                        new
                        {
                            CategoryId = 9,
                            Color = "#52C41A",
                            CreatedAt = new DateTime(2025, 12, 18, 16, 25, 35, 393, DateTimeKind.Utc).AddTicks(9660),
                            Icon = "💰",
                            Name = "Salary",
                            Type = "Income"
                        },
                        new
                        {
                            CategoryId = 10,
                            Color = "#13C2C2",
                            CreatedAt = new DateTime(2025, 12, 18, 16, 25, 35, 393, DateTimeKind.Utc).AddTicks(9661),
                            Icon = "💼",
                            Name = "Freelance",
                            Type = "Income"
                        },
                        new
                        {
                            CategoryId = 11,
                            Color = "#1890FF",
                            CreatedAt = new DateTime(2025, 12, 18, 16, 25, 35, 393, DateTimeKind.Utc).AddTicks(9662),
                            Icon = "📈",
                            Name = "Investment",
                            Type = "Income"
                        },
                        new
                        {
                            CategoryId = 12,
                            Color = "#EB2F96",
                            CreatedAt = new DateTime(2025, 12, 18, 16, 25, 35, 393, DateTimeKind.Utc).AddTicks(9664),
                            Icon = "🎁",
                            Name = "Gift",
                            Type = "Income"
                        },
                        new
                        {
                            CategoryId = 13,
                            Color = "#52C41A",
                            CreatedAt = new DateTime(2025, 12, 18, 16, 25, 35, 393, DateTimeKind.Utc).AddTicks(9665),
                            Icon = "💵",
                            Name = "Other Income",
                            Type = "Income"
                        });
                });

            modelBuilder.Entity("SmartExpense.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TransactionId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("SmartExpense.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartExpense.Models.Category", b =>
                {
                    b.HasOne("SmartExpense.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartExpense.Models.Transaction", b =>
                {
                    b.HasOne("SmartExpense.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartExpense.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartExpense.Models.Category", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
